model: "MACE"
foundation_model: "/home/rat/Nancy_D/SNAR_v3/MACE/MACE_models/mace_B3LYP_SNAR_it1_stagetwo.model"
num_channels: 128
max_L: 1
r_max: 5.0
name: "mace_B3LYP_SNAR_it2"
model_dir: "/home/rat/Nancy_D/SNAR_v3/MACE/MACE_models"
log_dir: "/home/rat/Nancy_D/SNAR_v3/MACE/MACE_models"
checkpoints_dir: "/home/rat/Nancy_D/SNAR_v3/MACE/MACE_models"
results_dir: "/home/rat/Nancy_D/SNAR_v3/MACE/MACE_models"
train_file: "/home/rat/Nancy_D/SNAR_v3/MACE/dft_train.xyz"
valid_fraction: 0.10
test_file: "/home/rat/Nancy_D/SNAR_v3/MACE/dft_test.xyz"
energy_key: "energy_dft"
forces_key: "forces_dft"
device: cuda
enable_cueq: True
batch_size: 40
max_num_epochs: 1500
swa: True
start_swa: 1250
seed: 123
restart_latest: True
lr: 0.001